name: X
on:
  issues:
    types: [closed]

jobs:
  X:
    runs-on: ubuntu-latest
    if: github.event.issue.state_reason == 'completed' && github.event.sender.login == 'Ryoga-exe'
    steps:
      - name: Generate ct0
        id: gen_ct0
        env:
          auth_token: ${{ secrets.auth_token }}
        run: |
          curl -s -I https://x.com/home \
          -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36' \
          -b "auth_token=$auth_token" \
          | grep ct0 \
          | sed 's/.*ct0=\([a-f0-9]*\).*/ct0=\1/' >> $GITHUB_OUTPUT
      - name: X
        env:
          auth_token: ${{ secrets.auth_token }}
        run: |
          curl 'https://x.com/i/api/graphql/IVdJU2Vjw2llhmJOAZy9Ow/CreateTweet' \
          -H 'authorization: Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA' \
          -H 'content-type: application/json' \
          -b "auth_token=$auth_token; ct0=${{ steps.gen_ct0.outputs.ct0 }}" \
          -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36' \
          -H 'x-csrf-token: ${{ steps.gen_ct0.outputs.ct0 }}' \
          --data-raw '{"variables":{"tweet_text":"${{ github.event.issue.title }}","dark_request":false,"media":{"media_entities":[],"possibly_sensitive":false},"semantic_annotation_ids":[],"disallowed_reply_options":null},"features":{"premium_content_api_read_enabled":false,"communities_web_enable_tweet_community_results_fetch":true,"c9s_tweet_anatomy_moderator_badge_enabled":true,"responsive_web_grok_analyze_button_fetch_trends_enabled":false,"responsive_web_grok_analyze_post_followups_enabled":true,"responsive_web_jetfuel_frame":false,"responsive_web_grok_share_attachment_enabled":true,"responsive_web_edit_tweet_api_enabled":true,"graphql_is_translatable_rweb_tweet_is_translatable_enabled":true,"view_counts_everywhere_api_enabled":true,"longform_notetweets_consumption_enabled":true,"responsive_web_twitter_article_tweet_consumption_enabled":true,"tweet_awards_web_tipping_enabled":false,"responsive_web_grok_show_grok_translated_post":false,"responsive_web_grok_analysis_button_from_backend":true,"creator_subscriptions_quote_tweet_preview_enabled":false,"longform_notetweets_rich_text_read_enabled":true,"longform_notetweets_inline_media_enabled":true,"profile_label_improvements_pcf_label_in_post_enabled":true,"rweb_tipjar_consumption_enabled":true,"responsive_web_graphql_exclude_directive_enabled":true,"verified_phone_label_enabled":false,"articles_preview_enabled":true,"responsive_web_graphql_skip_user_profile_image_extensions_enabled":false,"freedom_of_speech_not_reach_fetch_enabled":true,"standardized_nudges_misinfo":true,"tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled":true,"responsive_web_grok_image_annotation_enabled":true,"responsive_web_graphql_timeline_navigation_enabled":true,"responsive_web_enhance_cards_enabled":false}}' \
          jq -e '.errors' && \
          exit 1
